title: My Awesome Title
author: imcarolyn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Description goes here! This is my description!

# social links
twitter_username: imcarolyn
github_username:  imcarolyn

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
